
@apiUrl = http://localhost:3000

// token admin pour les tests
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImVtYWlsIjoiYmlsYWxlbGhhZGRhZGkucHJvQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcxNjI4Nzc0MywiZXhwIjoxNzE2MjkxMzQzfQ.8HKne881XLXEf3Jb0eaxrSdgtaLlamN31absS9BqYFU

### Création d'un nouveau code promo
# Crée un code promo avec le code "TEST_CODE_PROMO", un rabais de 15%, 
# actif du 1er juin 2021 au 31 août 2021, et marqué comme actif.
POST {{apiUrl}}/promoCode/createCodePromo
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "code": "TEST_PROMO_CODE",
  "discount": 15,
  "start_date": "2021-06-01",
  "end_date": "2021-08-31",
  "is_active": true
}



### Récupération de tous les codes promo
# Récupère la liste de tous les codes promo disponibles dans la base de données.
GET {{apiUrl}}/promoCode/getAllPromoCodes
Authorization: Bearer {{token}}


### Suppression d'un code promo
# Supprime le code promo ayant l'identifiant spécifique 12.
DELETE {{apiUrl}}/promoCode/deletePromoCode/13
Authorization: Bearer {{token}}


### Mise à jour d'un code promo
# Met à jour le code promo avec l'ID 12 pour changer son code en "ASUS22",
# le rabais à 20%, actif du 1er septembre 2022 au 30 novembre 2022,
# et le marque comme inactif.
PUT {{apiUrl}}/promoCode/updatePromoCode/12
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "ASUS22",
  "discount": 20,
  "start_date": "2022-09-01",
  "end_date": "2022-11-30",
  "is_active": false
}

