@apiUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImVtYWlsIjoiYmlsYWxlbGhhZGRhZGkucHJvQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcxNjI4Nzc0MywiZXhwIjoxNzE2MjkxMzQzfQ.8HKne881XLXEf3Jb0eaxrSdgtaLlamN31absS9BqYFU


### Créer une Nouvelle Formation
# Crée une nouvelle formation avec les détails spécifiés.
POST {{apiUrl}}/formation/addFormation HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nomFormation": "formation en test",
    "description": "Apprenez à créer des applications web complètes avec Node.js, React, et plus encore. etc...",
    "niveau": "Intermédiaire",
    "prix": 25,
    "duree": 3,
    "prerequis": "master en testing"
}

### Obtenir Toutes les Formations avec leurs Sessions
# Récupère toutes les formations et leurs sessions respectives si elles en ont.
GET {{apiUrl}}/formation/getAllFormationsWithSessions HTTP/1.1

### Obtenir une Formation par ID
# Récupère les détails d'une formation spécifique par son ID.
GET {{apiUrl}}/formation/getFormationById/2 HTTP/1.1

### Obtenir des Formations Similaires
# Récupère des formations similaires à la formation spécifiée par ID.
GET {{apiUrl}}/formation/getSimilarFormation/2 HTTP/1.1

### Mettre à Jour une Formation
# Met à jour les détails d'une formation spécifique par son ID.
PUT {{apiUrl}}/formation/updateFormation/31 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomFormation": "Développement Web Avancé",
    "description": "Une description mise à jour sur les techniques avancées de développement web.",
    "niveau": "Avancé",
    "prix": 1500,
    "duree": 45,
    "prerequis": "Connaissance de base en HTML, CSS, et JavaScript"
}

### Supprimer une Formation
# Supprime une formation spécifique par son ID.
DELETE {{apiUrl}}/formation/deleteFormation/31 HTTP/1.1
Authorization: Bearer {{token}}
