### Test de l'inscription d'un utilisateur particulier
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "bilal.el.haddadi76@gmail.com",
  "adresse": "123 Rue de la Liberté",
  "type": "Particulier",
  "nom": "Doe",
  "prenom": "John",
  "password": "aze"
}






### Test de l'inscription d'un utilisateur particulier
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "test34@example.com",
  "adresse": "123 Rue de la Liberté",
  "type": "Particulier",
  "nom": "billy",
  "prenom": "aze",
  "password": "aze"
}

//https://test-backend-gluw.onrender.com/users/register
###
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "bilal.elhaddadi@student.vinci.be",
  "adresse": "123 Rue Exemple",
  "type": "Entreprise",
  "numero_telephone": "0123456789",
  "nom": "Doe",
  "prenom": "John",
  "password": "123123aze"
}



###verif status de user 
GET https://test-backend-gluw.onrender.com/clients/verify?token=7122c582-5a49-4876-a4ca-981e2b2ece1a
//http://localhost:3000/clients/verify?token=${token}
###
GET http://localhost:3000/clients/verify?token=6ce5274d-22a0-415d-a5df-c6db2d6b9a82


### Test de l'inscription d'un utilisateur entreprise
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "bilal.elhaddadi@student.vinci.be",
  "adresse": "456 Avenue des Entreprises",
  "type": "Entreprise",
  "numero_telephone":123456789,
  "nom_entreprise": "TechCorp",
  "numero_tva": "FR123456789",
  "password": "aze",
  "numero_entreprise":"123123",
  "adresse_facturation":"adresse facturation 12"
}

### Test de la route de vérification de l'utilisateur
GET http://localhost:3000/clients/verify?token=95e109cd-46f1-4374-976b-aa558f3f3dfd

### Test de l'inscription d'un utilisateur entreprise
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "bilal.elhaddadi@student.vinci.be",
  "adresse": "456 Avenue des Entreprises",
  "type": "Entreprise",
  "nom_entreprise": "test",
  "numero_tva": "FR123456789",
  "password": "aze"
}



### Test de la connexion d'un utilisateur
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "bilalelhaddadi.pro@gmail.com",
  "password": "aze"
}

### Test de la connexion d'un utilisateur
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "bilal.el.haddadi77@gmail.com",
  "password": "aze"
}

//https://test-backend-gluw.onrender.com



### Test de la connexion d'un utilisateur backend deploye
POST https://test-backend-gluw.onrender.com/users/login
Content-Type: application/json

{
  "email": "billy@example.com",
  "password": "aze"
}

###
PUT http://localhost:3000/users/updateUser/38
Content-Type: application/json

{
  "newPassword": "aze",
  "adresse": "123 rue de l'Exemple, 75000 Paris",
  "type": "Particulier",
  "prenom": "aaa",
  "nom_entreprise": "",
  "numero_tva": ""
}

###
GET http://localhost:3000/users/clientInfo/39


//https://test-backend-gluw.onrender.com/users/register

###
POST http://localhost:3000/users/request-reset
Content-Type: application/json

{
  "email": "karimrudi9@gmail.com"
}


###
POST http://localhost:3000/users/reset-password
Content-Type: application/json

{
  "token": "7b13530f-fa62-4573-9dfc-a94e73c61320",
  "newPassword": "aze123aze"
}