### Test de l'inscription d'un utilisateur particulier
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "bilal.el.haddadi76@gmail.com",
  "adresse": "123 Rue de la Liberté",
  "type": "Particulier",
  "nom": "Doe",
  "prenom": "John",
  "password": "aze"
}

### Test de l'inscription d'un utilisateur particulier
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "billy@example.com",
  "adresse": "123 Rue de la Liberté",
  "type": "Particulier",
  "nom": "billy",
  "prenom": "aze",
  "password": "aze"
}


### Test de l'inscription d'un utilisateur entreprise
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "entreprise@example.com",
  "adresse": "456 Avenue des Entreprises",
  "type": "Entreprise",
  "nom_entreprise": "TechCorp",
  "numero_tva": "FR123456789",
  "password": "aze"
}

### Test de l'inscription d'un utilisateur entreprise
POST https://test-backend-gluw.onrender.com/users/register
Content-Type: application/json

{
  "email": "test@example.com",
  "adresse": "456 Avenue des Entreprises",
  "type": "Entreprise",
  "nom_entreprise": "test",
  "numero_tva": "FR123456789",
  "password": "aze"
}



### Test de la connexion d'un utilisateur
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "billy@example.com",
  "password": "aze"
}



### Test de la connexion d'un utilisateur
POST https://test-backend-gluw.onrender.com/users/login
Content-Type: application/json

{
  "email": "billy@example.com",
  "password": "aze"
}

//https://test-backend-gluw.onrender.com/users/register