### Test de Création d'une Intention de Paiement avec Stripe

POST http://localhost:3000/stripe/create-payment-intent
Content-Type: application/json

{
    "price": 1, 
    "currency": "eur",
    "payment_method_types": "card"
}

###
POST http://localhost:3000/stripe/create-payment-intent-formation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlbnRyZXByaXNlQGV4YW1wbGUuY29tIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTcwNzkxNzIxNiwiZXhwIjoxNzA3OTIwODE2fQ.N0hNwj2lgCYmMLmiCPuy8digqEZDqLWwPlwRwKULr9U
Content-Type: application/json

{
    "price": 1, 
    "currency": "eur",
    "payment_method_types": "card"
}


### Création d'une intention de paiement pour une formation
POST http://localhost:3000/stripe/create-payment-intent-formation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImVtYWlsIjoiYmlsYWwuZWwuaGFkZGFkaTc2QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA3Mjk4MzA0LCJleHAiOjE3MDczMDE5MDR9.lLIeRI8M8MtKjwgGFsK2pz6QXqbf761-CCIH42ZVqpk

{
    "formationId": 1,
    "price": 10,
    "clientId": 21
}


### Création d'une intention de paiement pour une formation
POST http://localhost:3000/stripe/create-payment-intent-formation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImVtYWlsIjoiYmlsYWxlbGhhZGRhZGkucHJvQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcwODY4MDA4MCwiZXhwIjoxNzA4NjgzNjgwfQ.2GEm7YKa8PP9N50CFExE31ase5UyAiAu-pNR_jjzFhI

{
    "formationId": 8,
    "clientId": 38,
    "promoCode": "WELCOME10"

}

###
POST http://localhost:3000/stripe/create-paypal-payment
Content-Type: application/json

{
    "price": "11.00"
}
